import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import Link from 'next/link'


export default function Home() {
  const [menu,setMenu] = useState("none")

  const handleMenu =()=>{
    if (menu == "none") {
      setMenu("inline")
    }else{
      setMenu("none")
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap" rel="stylesheet"/>
      </Head>
      <main className={styles.app}>
        <div className={styles.nav}>

          <div className={styles.nav1}>
            <div className={styles.nav1Container}>
            <div className={styles.navS1}>
              <p className={styles.text}>Le choix d'un partenaire fiable</p>
            </div>
            <div className={styles.navS2}>
              <p className={styles.text2} style={{display:'flex',alignItems:"center"}}> <p className={styles.text}>Appelez-nous:</p>+212 6 59 85 35 33</p>
              <p className={styles.text2} style={{display:'flex',alignItems:"center"}}> <p className={styles.text}>Envoyez-nous un mail:</p> avenaservices@gmail.com</p>
            </div>
          </div>
          </div>

          <div className={styles.nav2}>
            <div className={styles.nav2S1}>
              <Image width={75} height={75} src="/assets/logoW.jpeg" />
            </div>

            <div className={styles.nav2S2}>
            <Link style={{textDecoration:"none"}} href="/"><p className={styles.page}>Home</p></Link>
            <Link style={{textDecoration:"none"}} href="/apropre"><p className={styles.page}>A propos</p></Link>
              <p className={styles.page}>Nos services</p>
              <Link style={{textDecoration:"none"}} href="/"><p className={styles.page}>Prestation</p></Link>
              <Link style={{textDecoration:"none"}} href="/Contact"><p className={styles.page}>Contact</p></Link>
            </div>

            <div className={styles.nav2S3}>
              <button className={styles.devisButton}>Demandez un devis</button>
            </div>
          </div>
        </div>
        <div className={styles.navPhone}>
        <div className={styles.nav2S1}>
              <Image style={{marginLeft:"20px"}} width={75} height={75} src="/assets/logoW.jpeg" />
        </div>
        <div>
          <img onClick={handleMenu} style={{width:"40px",height:"40px",marginRight:"20px",cursor:"pointer"}} src="/assets/bar.png" alt="" />
        </div>
        </div>
        <div style={{display:menu}} className={styles.menu}>
          <div className={styles.menuList}>
            <center>
            <Link style={{textDecoration:"none",marginBottom:"20px"}} href="/"><p className={styles.page}>Home</p></Link>
            <Link style={{textDecoration:"none",marginBottom:"20px"}} href="/apropre"><p className={styles.page}>A propos</p></Link>
              <p style={{marginBottom:"20px"}} className={styles.page}>Nos services</p>
              <Link style={{textDecoration:"none",marginBottom:"20px"}} href="/equipements"><p className={styles.page}>Prestation</p></Link>
              <Link style={{textDecoration:"none",marginBottom:"20px"}} href="/Contact"><p className={styles.page}>Contact</p></Link>

            </center>
          </div>
        </div>



        <div className={styles.secssion1}>
          <div className={styles.sec1Container}>
            <div className={styles.s1}>
              <img style={{width:"100%",minWidth:"350px",marginBottom:"10px"}} src="/assets/apropre2.webp"/>
            </div>
            <div className={styles.s2}>
              <p style={{fontWeight:"bold",fontSize:"17px",letterSpacing:"0.5px",color:"#424242"}}>À propos</p><br />
              <h1 style={{color:"#082680",fontWeight:"bold",marginBottom:"10px",fontSize:"35px"}}>LAISSEZ-NOUS FAIRE LE TRAVAIL</h1>
              <p style={{fontWeight:500,color:"#4C4C4C",fontSize:"17px",lineHeight:"25px"}}>AVENA Services est une société spécialisée dans le nettoyage, gardiennage et l'entretien des locaux professionnels et particuliers, nous proposons des services adaptés à toutes vos contraintes et spécificités dans vos locaux professionnels. Notre engagement est de vous offrir une prestation irréprochable à moindre prix.</p>
              
            </div>
          </div>
        </div>


      </main>
    </>
  )
}
